### ISSUE TITLE
Update DPNP integration

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#348]
Revert #347.
- [x]  Use DPNP 0.6.0 on Python 3.7 and Python 3.8 #357 
- [x] Enable DPNP on Python 3.8 #359
- [x] Update developers guide about dpnp integration key issues #362
- [x] Update DPNP features #383

**Comment by PokhodenkoSA** [comment]
Implemented in 0.15.0
