### ISSUE TITLE
Support Numba 0.55

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#582]
Numba 0.55 is not released yet. Use master branch.

- [x] Test w/ numba 0.55 in public CI #583 
- [x] Update code for support numba 0.55 #583 
  - [x] #643 
  - [x] #592
- [x] Test w/ important PRs
  - [x] #586
  - [x] #584 
  - [x] #585 - to merge after numba merge
  - [x] Support Numba #7421 - https://github.com/IntelPython/numba-dppy/actions/runs/1342911213

Wait for updates and run manual workflow:
https://github.com/IntelPython/numba-dppy/actions/workflows/numba.yml

**Comment by 1e-to** [comment]
Problem with python 3.8: https://github.com/IntelPython/numba-dppy/issues/592
